name: Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      working-directory: ./backend
      run: make install

    - name: test
      working-directory: ./backend
      run: make testing
